# Numpy Module

+ numpy for math 
+ pandas for data
+ matlab for grap

In [ ]:
import numpy as np

In [ ]:
'''
radian / degree = pi / 180 
so ..
radian = degree * pi / 180 
degree = radian * 180 / pi
'''

# pi / 180 : to convert from degrees to radians
print(np.sin(30*np.pi/180))

# 180 / pi : to convert from radians to degrees

# or ---------------------------------------

print(np.sin(np.deg2rad(30)))

In [ ]:
# round 
'''
0.6 to 0.9 are ceil
0.1 to 0.5 are floor
'''
print(np.round(2.4)) # 2
print(np.round(2.5)) # 2
print(np.round(2.6)) # 3

In [ ]:
# floor 
print(np.floor(2.7)) # 2
print(np.floor(2.3)) # 2

In [ ]:
# ceil 
print(np.ceil(2.7)) # 3
print(np.ceil(2.3)) # 3

In [ ]:
# mod(n1,n2) = n1 % n2
print(np.mod(31,5)) # 1

In [ ]:
# power(base,power)
print(np.power(2,3)) # 8

In [ ]:
# arrays
ls = [1,2,3,5,4]
arr = np.array(ls)
print(ls) # [1, 2, 3, 5, 4]
print(arr) # [1 2 3 5 4]

In [ ]:
ls = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(ls)
print(ls) # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(arr)
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''

In [ ]:
# array one line
arr = np.array([range(i,i+3) for i in [1,5,8]])
print(arr)
'''
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
'''

arr = np.array([range(i,i+4) for i in [1,5,8]])
print(arr)
'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
'''

arr = np.array([range(i,i+4) for i in [1,5,8,12]])
print(arr)
'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]
 [12 13 14 15]]
'''

In [ ]:
# determine data type
print(np.array([('elsayed', 20,3.8,'male'),('mhmd', 22,3.9,'male'),('ahmed',19,3.6,'male'),('mona',20,3.7,'female')],dtype=[('name',"7U"),('age','i2'),('gpa','f2'),('gander','6U')]))

# error
# determine data type
print(np.array([('elsasfdfgyed', 20,3.8,'male'),('mhmd', 22,3.9,'male'),('ahmed',19,3.6,'male'),('mona',20,3.7,'female')],dtype=[('name',"7U"),('age','i2'),('gpa','f2'),('gander','6U')]))
# only print 7 digit from elsasfd

In [ ]:
# np.empty((row,colum))
print(np.empty((2,3))) # empty matrix 2 rows and 3 columns

In [ ]:
# np.random.random((row,colum))
print(np.random.random((2,3))) # return numbers form 0 to 1 as matrix 2 rows and 3 columns
'''
[[0.20751384 0.82559592 0.39591979]
 [0.24221651 0.75545912 0.13936819]]
'''

print(np.random.random((2,3))*10) # return numbers form 0 to 10 as matrix 2 rows and 3 columns
'''
[[6.04249428 1.15402611 1.54676542]
 [0.51647152 6.93058527 0.77727209]]
'''

print(np.random.random((2,3))*10+10) # return numbers form 10 to 20 as matrix 2 rows and 3 columns
'''
[[14.05312344 19.959442   11.93720631]
 [19.42369319 17.23358505 10.62668063]]
'''

print((np.random.random((2,3))+10)*10) # return numbers form 100 to 110 as matrix 2 rows and 3 columns
'''
[[100.56889213 109.94290104 108.16330322]
 [100.9678728  100.61369151 102.62310933]]
'''

print(np.random.random((2,3))*100+200) # return numbers form 200 to 300 as matrix with 2 rows and 3 columns
'''
[[296.31148902 289.43900727 205.08235474]
 [290.07673613 260.99400656 255.77594445]]
'''

In [ ]:
# np.random.uniform(low,high,count) return as list
print(np.random.uniform(1,10,15)) # 15 random numbers from 1 to 10

ls1 = np.random.uniform(1,10,16)
ls2 = np.random.uniform(1,10,6)
ls2.sort()
print(np.array(ls1))
print(np.array(ls2))

In [ ]:
# normal distribution >> np.random.normal(start,end,count)
print(np.random.normal(5,10,8)) # return 8 numbers form 5 to 10 as list
'''
[ 2.68982212  1.06521118  9.13914003 -3.36241647 -1.86114438 15.30888735
 11.63440426 -6.92532138]
'''

In [ ]:
# np.random.randint(range)
print(np.random.randint(200)) # random number from 0 to 199
# 182

In [ ]:
print(np.random.randint(200,size=5)) # random matrix 2 rows and 5 columns with numbers  numbers from 0 to 199
# [107  62 192 134 118]

In [ ]:
print(np.random.randint(100,200,size=8)) # random matrix 1 rows and 8 columns with numbers from 100 to 199
# [176 149 194 126 144 182 125 155]

In [ ]:
print(np.random.randint(100,200,size=(2,5))) # random matrix 2 rows and 5 columns with numbers from 100 to 199
'''
[[116 144 156 114 121]
 [163 143 115 178 131]]
'''

In [ ]:
print(np.random.randint(100,200,size=(2,5,3))) # random matrix 2 layers and 5 rows and 3 columns with numbers from 100 to 199
'''
[[[136 126 171]
  [194 118 116]
  [185 168 173]
  [107 123 126]
  [185 112 182]]

 [[137 130 132]
  [155 165 196]
  [179 187 107]
  [138 148 166]
  [159 150 156]]]
'''

In [ ]:
print(np.random.randint(100,200,size=(3,5,4))) # random matrix 3 layers and 5 rows and 4 columns with numbers from 100 to 199
'''
[[[171 105 166 186]
  [149 186 186 110]
  [197 100 147 169]
  [172 100 100 166]
  [162 169 112 129]]

 [[122 112 164 191]
  [121 180 164 178]
  [150 186 177 118]
  [124 192 139 186]
  [138 174 139 138]]

 [[143 195 114 106]
  [179 182 115 100]
  [180 184 117 177]
  [164 172 131 101]
  [179 184 195 125]]]
'''

In [ ]:
# reshape(list,(rows,columns))
ls = np.random.randint(10,20,8)
arr = np.reshape(ls,(2,4))

print(ls)
# [11 14 16 15 18 19 16 17]

print(arr)
'''
[[11 14 16 15]
 [18 19 16 17]]
'''

In [ ]:
# random.rand(layout,rows,cols)
print(np.random.rand(2,4,3))
'''
[[[0.98614    0.61208242 0.98296403]
  [0.29835686 0.65584079 0.60002409]
  [0.81230996 0.76082099 0.03954777]
  [0.62977305 0.11677823 0.51369862]]

 [[0.84009958 0.8509469  0.58316351]
  [0.79642463 0.22215372 0.59250504]
  [0.95072422 0.81211105 0.55567093]
  [0.49362475 0.04736241 0.04381471]]]
'''

In [ ]:
# random.choice(list)
ls = ['a',1,True,1.5,False,'Hello']
print(np.random.choice(ls))

In [ ]:
# random.shuffle(list)
ls = [1,2,3,4,5,6,7,8,9]
print(ls) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.random.shuffle(ls)
print(ls) # [3, 9, 1, 2, 8, 4, 6, 5, 7]

In [ ]:
# zeros(layout,rows,cols)
print(np.zeros(5)) # 1D
# [0. 0. 0. 0. 0.]
print(np.zeros((5,6))) # 2D
'''
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
'''
print(np.zeros((2,5,6))) # 3D
'''
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
'''


In [ ]:
# ones(layout,rows,cols)
print(np.ones(6)) # 1D
# [1. 1. 1. 1. 1. 1.]

print(np.ones((4,2))) # 2D
'''
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
'''
print(np.ones((2,3,5))) # 3D
'''
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
'''

In [ ]:
# eye(rows,cols) : Identity matrix
print(np.eye(5))
'''
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
'''

In [ ]:
print(np.eye(5,6))
'''
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
'''

In [ ]:
# full((rows, cols), number)
print(np.full((5,3),7))
'''
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
'''

In [ ]:
# arange(start=0,end).reshape(rows,cols,layout)
print(np.arange(27).reshape(3,3,3))
'''
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
'''

In [ ]:
# linspace(start, end, count=50) # include end # count default 50
print(np.linspace(10,20)) # 50 number in matrix from 10 to 20  
'''
[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
'''

In [ ]:
print(np.linspace(10,20,5)) 
'''
[10.  12.5 15.  17.5 20. ]
''' 

In [ ]:
print(np.linspace(10,20,6).reshape(2,3)) 
'''
[[10. 12. 14.]
 [16. 18. 20.]]
'''


In [ ]:
#  diag(array([2,5,4,56,68],k=2) # k = 2 => add two rows and two cols zeros on matrix
print(np.diag([2,3,6,5,8]))
'''
[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 6 0 0]
 [0 0 0 5 0]
 [0 0 0 0 8]]
'''

In [ ]:
print(np.diag([2,3,6,5,8],k=3)) # add 3 rows and 3 columns zeros
'''
[[0 0 0 2 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 8]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
'''

In [ ]:
# count_nonzero(condition)
mat = np.random.randint(0,10,(3,5))
print(mat)
'''
[[5 4 2 0 3]
 [3 0 3 7 0]
 [9 4 2 3 9]]
'''
print(np.count_nonzero(mat)) # 12

In [ ]:
mat = np.random.randint(0,10,(3,5))
print(mat)
'''
[[7 9 9 2 5]
 [3 7 7 1 3]
 [1 1 7 8 5]]
'''
print(np.count_nonzero(mat > 5)) # 7

In [ ]:
mat = np.random.randint(10,30,(3,4))
print(mat)
'''
[[20 19 26 16]
 [19 16 19 16]
 [28 11 25 29]]
'''
print(np.count_nonzero(mat>20,axis=1)) # [1 0 3]

In [ ]:
# any(condition) : return true if any value true otherwise false
mat = np.random.randint(10,30,(3,4))
print(mat)
'''
[[15 12 24 15]
 [26 17 26 27]
 [27 29 29 26]]
'''
print(np.any(mat > 20)) # True

print(np.any(mat > 20,axis = 1)) # [ True  True  True]


In [ ]:
# all(condition) : return true if all value true otherwise false

mat = np.random.randint(10,30,(3,4))
print(mat)
'''
[[14 27 27 18]
 [10 15 25 19]
 [22 29 22 20]]
'''
print(np.all(mat > 20)) # False

print(np.all(mat > 20,axis = 1)) # [False False False]

In [ ]:
a = np.random.randint(5,25,10).reshape(2,5)
b = a[a>20]
c = a[a<20]
print(a)
'''
[[23 10  7 21  9]
 [ 7 23  5 20 15]]
'''
print(b)
# [23 21 23]
print(c)
# [10  7  9  7  5 15]

In [ ]:
# isclose(matrix1 , matrix2, rtol= 0.5) 
'''
compare between matrix1 and matrix2 and 
if difference is only 0.5 then return True
otherwise return False
'''
a = np.arange(15).reshape(3,5) # not include 15 
b = np.arange(15).reshape(3,5)
c = np.arange(15).reshape(3,5)*2
ab = np.isclose(a, b,rtol = 0.5)
ac = np.isclose(a, c,rtol = 0.3)
print(a)
'''
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
'''
print(b)
'''
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
'''
print(c)
'''
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
'''
print(ab)
'''
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
'''
print(ac)
'''
[[ True False False False False]
 [False False False False False]
 [False False False False False]]
'''

In [ ]:
# multiply(matrix , number, out )
a = np.arange(7)
b = np.empty(7)
print(a)
'''
[0 1 2 3 4 5 6]
'''
print(b)
'''
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]
'''
np.multiply(a,10,out=b)
print(b)
'''
[ 0. 10. 20. 30. 40. 50. 60.]
'''

In [ ]:
# multiply(matrix , number, out )
a = np.arange(7)
b = np.empty(7)
print(a)
'''
[0 1 2 3 4 5 6]
'''
print(b)
'''
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]
'''
c = np.multiply(a,10)
print(c)
# [ 0 10 20 30 40 50 60]

In [ ]:
# multiply.reduce(matrix) return multiply all numbers
a = np.arange(2,7) # [2 3 4 5 6]
print(np.multiply.reduce(a)) # 720

In [ ]:
# multiply.outer(matrix1 , matrix2)
a = np.arange(7) # [0 1 2 3 4 5 6]
b = np.arange(7) # [0 1 2 3 4 5 6]
c = np.multiply.outer(a,b)
'''
[[0*0 0*1 0*2 0*3 0*4 0*5 0*6]
 [1*0 1*1 1*2 1*3 1*4 1*5 1*6]
 [2*0 2*1 2*2 2*3 2*4 2*5 2*6]
 [3*0 3*1 3*2 3*3 3*4 3*5 3*6]
 [4*0 4*1 4*2 4*3 4*4 4*5 4*6]
 [5*0 5*1 5*2 5*3 5*4 5*6 5*6]
 [6*0 6*1 6*2 6*3 6*4 6*5 6*6]]
'''
print(c)
'''
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6]
 [ 0  2  4  6  8 10 12]
 [ 0  3  6  9 12 15 18]
 [ 0  4  8 12 16 20 24]
 [ 0  5 10 15 20 25 30]
 [ 0  6 12 18 24 30 36]]
'''

In [ ]:
# multiply.accumulate(matrix) ~ same factorial
a = np.arange(1,7) # [1 2 3 4 5 6]
print(np.multiply.accumulate(a))
'''
[1 2*1 3*2*1 4*3*2*1  5*4*3*2*1 6*5*4*3*2*1]
'''
'''
[1 2 6 24 120 720]
'''

In [ ]:
# power(matrix , power, out)
a = np.arange(7)
b = np.empty(7)
print(a)
'''
[0 1 2 3 4 5 6]
'''
print(b)
'''
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]
'''
c = np.power(a,3)
print(c)
# [  0   1   8  27  64 125 216]

In [ ]:
# add(matrix , number, out)
a = np.arange(7)
b = np.empty(7)
print(a)
'''
[0 1 2 3 4 5 6]
'''
print(b)
'''
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]
'''
c = np.add(a,7)
print(c)
# [ 7  8  9 10 11 12 13]

In [ ]:
# add.reduce(matrix) return collection numbers
a = np.arange(7) # [0 1 2 3 4 5 6]
print(np.add.reduce(a)) # 21

In [ ]:
# add.accumulate(matrix) return matrix with collection all back 
a = np.arange(2,7) # [2 3 4 5 6]
print(np.add.accumulate(a))
'''
[2 3+2 4+3+2 5+4+3+2 6+5+4+3+2]
'''
'''
[2 5 9 14 20]
'''

In [ ]:
# len(matrix) 
a = np.arange(5) # [0 1 2 3 4]
print(len(a)) # 5

b = np.arange(6).reshape(3,2)
'''
[[0 1]
 [2 3]
 [4 5]]
'''
print(len(b)) # = count rows = 3

In [ ]:
# size(matrix)
a = np.arange(5) # [0 1 2 3 4]
print(np.size(a)) # 5

b = np.arange(6).reshape(3,2)
'''
[[0 1]
 [2 3]
 [4 5]]
'''
print(np.size(b)) # = count all number in rows and cols = 6

In [ ]:
# shape(matrix)
a = np.arange(5) # [0 1 2 3 4]
print(np.shape(a)) # (5, ) because not reshape it

b = np.arange(6).reshape(3,2)
'''
[[0 1]
 [2 3]
 [4 5]]
'''
print(np.shape(b)) # = shape rows and cols = (3,2)

In [ ]:
# ndim(matrix) = nmber of dimensional 
a = np.arange(5) # [0 1 2 3 4]
print(np.ndim(a)) # 1

b = np.arange(6).reshape(3,2)
'''
[[0 1]
 [2 3]
 [4 5]]
'''
print(np.ndim(b)) # 2

c = np.arange(27).reshape(3,3,3) # not include 27 = 0 to 26 
print(c)
'''
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
'''
print(np.ndim(c)) # 3

In [ ]:
# dtype(matrix)
a = np.arange(7) # [0 1 2 3 4 5 6]
print(a.dtype) # int64 > integer 64 bit

b = np.arange(6).reshape(3,2)
'''
[[0 1]
 [2 3]
 [4 5]]
'''
print(b.dtype) # int64

c = np.array(['a', 'b'])
print(c.dtype) # U1

In [ ]:
# matrix
print(np.matrix([i for i in range(10)]).reshape(2,5))

print(np.matrix('{} {} {} {} {} ; {} {} {} {} {}'.format(0,1,2,3,4,5,6,7,8,9)))

In [ ]:
# trace(matrix) collection diagonal 
print(np.trace(np.eye(5))) # 1+1+1+1+1 = 5 
'''
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
'''

print('*'*20)

print(np.arange(9).reshape(3,3))
'''
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(np.trace(np.arange(9).reshape(3,3))) # 12

print('*'*20)

print(np.arange(27).reshape(3,3,3))
'''
[[[ 0  1  2] # this 
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14] #  + this
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] #  + this
'''
print(np.trace(np.arange(27).reshape(3,3,3))) # [36 39 42] 

In [ ]:
# linalg.det(matrix)
a = np.arange(1,5).reshape(2,2)
'''
[[1 2]
 [3 4]]
'''
print(np.linalg.det(a)) # 1*4 - 2*3 = -2.0

b = np.arange(9).reshape(3,3) 
'''
  - + -
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(np.linalg.det(b)) # -0*(4*8 - 5*7) +1*(3*8 - 5*6) -2*(3*7 - 4*6) = 0.0

In [ ]:
# linalg.eig = eigenvalues 
a = np.arange(1,5).reshape(2,2)
'''
[[1 2]
 [3 4]]
'''
print(np.linalg.eig(a))

b = np.arange(9).reshape(3,3) 
'''
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(np.linalg.eig(b)) # ???????

In [ ]:
# slice
a = np.arange(2,9) # [2 3 4 5 6 7 8]
print(a[3]) # 5
print(a[-1]) # 8
print(a[::-2]) # [8 6 4 2]

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[3]) # [19 20 21 22 23 24]
print(a[-1]) #  [31 32 33 34 35 36]]
print(a[::-2])
'''
[[31 32 33 34 35 36]
 [19 20 21 22 23 24]
 [ 7  8  9 10 11 12]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[3,2]) # 21
print(a[2,:]) #  [13 14 15 16 17 18]

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

print(a[:,2]) #  [3 9 15 21 27 33]

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[:,2:4])
'''
[[3 4]
 [9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[1:4,:])
'''
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[:,-2]) # [5 11 17 23 29 35]

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[-1,:]) #  [31 32 33 34 35 36]]

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[:,:])
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[::-1,::-1])
'''
[[36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[2,4] = 0
print(a)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 #0 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[:,4] = 0
print(a)
'''
[[ 1  2  3  4  0  6]
 [ 7  8  9 10  0 12]
 [13 14 15 16  0 18]
 [19 20 21 22  0 24]
 [25 26 27 28  0 30]
 [31 32 33 34  0 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[3,:] = 0
print(a)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [ 0  0  0  0  0  0]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6) # [2 3 4 5 6 7 8]
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[:,:] = 0
print(a)
'''
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
'''

In [ ]:
a = np.arange(16).reshape(4,4)
b = a[2: , 3:] # change with a
print(a)
print(b)
a[:,:] = 7
print(a)
print(b)

In [ ]:
a = np.arange(16).reshape(4,4)
b = a[2: , 3:].copy() # not chaneg with a
print(a)
print(b)
a[:,:] = 7
print(a)
print(b)

In [ ]:
a = np.arange(27).reshape(3,3,3)
print(a)
'''
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
'''
print(a[1])
'''
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
'''
print(a[0,2]) # [6 7 8]
print(a[2,1,0]) # 21

In [ ]:
x = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
x1 , x2 ,x3 , x4= np.split(x, (2,3,4))
print(x1,x2,x3,x4) # [0 1] [2] [3] [4 5 6 7 8 9]

In [ ]:
x = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
x1 , x2 ,x3 , x4= np.split(x, (0,3,4))
print(x1,x2,x3,x4) # [] [0 1 2] [3] [4 5 6 7 8 9]

In [ ]:
x = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
x1 , x2 ,x3= np.split(x, (4,2))
print(x1,x2,x3) # [0 1 2 3] [] [2 3 4 5 6 7 8 9]

In [ ]:
# 2D [][]
x = np.arange(9).reshape(3,3)
'''
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(x[2][1]) # 7

In [ ]:
# vstack((matrix1,matrix2)) : must equal cols
a = np.arange(8).reshape(2,4)
b = 3*np.arange(8).reshape(2,4)
avb = np.vstack((a,b))
print(a)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
print(b)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
print(avb)
'''
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  3  6  9]
 [12 15 18 21]]
'''

In [ ]:
# hstack((matrix1,matrix2)) : must equal rows
a = np.arange(8).reshape(2,4)
b = 3*np.arange(8).reshape(2,4)
ahb = np.hstack((a,b))
print(a)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
print(b)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
print(ahb)
'''
[[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]]
'''

In [ ]:
# concatenate([matrix1,matrix2] , axis = 0 )  axis = 0 >> same vstack 
a = np.arange(8).reshape(2,4)
b = 3*np.arange(8).reshape(2,4)
ac0b = np.concatenate([a,b],axis=0)
print(a)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
print(b)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
print(ac0b)
'''
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  3  6  9]
 [12 15 18 21]]
'''

In [ ]:
# concatenate([matrix1,matrix2] , axis = 1) >> axis = 1 >> same hstack

a = np.arange(8).reshape(2,4)
b = 3*np.arange(8).reshape(2,4)
ac1b = np.concatenate([a,b],axis=1)
print(a)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
print(b)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
print(ac1b)
'''
[[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]]
'''

In [ ]:
# max(matrix)
# argmax(matrix)
a = np.random.randint(5,10,size = 8).reshape(2,4)
print(np.max(a))
print(np.argmax(a)) # position

In [ ]:
# min(matrix)
# argmin(matrix)
a = np.random.randint(5,10,size = 8).reshape(2,4)
print(np.min(a))
print(np.argmin(a)) # position

In [ ]:
# varience(matrix)
a = np.arange(7).reshape(1,7)
print(np.var(a)) # 4.0

In [ ]:
# covarience(matrix)
a = np.arange(8).reshape(2,4)
print(np.cov(a)) 
'''
[[1.66666667 1.66666667]
 [1.66666667 1.66666667]]
'''

In [ ]:
# dot(matrix) : multiply matrix
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(np.dot(a,b))
'''
[[ 42  48  54]
 [114 136 158]
 [186 224 262]]
'''

In [ ]:
# sum(matrix) : sum matrix
a = np.arange(12).reshape(3,4)
print(np.sum(a)) # 66
print(np.sum(a,axis = 0)) # [12 15 18 21]
print(np.sum(a,axis = 1)) # [6 22 38]

In [ ]:
# mean and standard deviation and varience
a = np.arange(12).reshape(3,4)
print(np.mean(a)) # 5.5
print(np.std(a)) # 3.4
print(np.var(a)) # 11.9

In [ ]:
# corrcoef(matrix)
a = np.random.randint(4,9,size = 12).reshape(3,4)
print(np.corrcoef(a))

In [ ]:
# sort(matrix , axis=0 or 1)
a = np.random.randint(4,9,size = 12).reshape(3,4)
print(np.sort(a, axis=0))
'''
[[4 5 5 5]
 [4 5 6 8]
 [5 6 8 8]]
'''
print(np.sort(a, axis=1))
'''
[[4 5 5 8]
 [4 6 6 8]
 [5 5 5 8]]
'''

In [ ]:
# linalg.inv(matrix) : linear algebra function
a = np.random.randint(5,15,size =9).reshape(3,3)
b = np.linalg.inv(a)
print(np.linalg.inv(a))
'''
[[-0.55504587  0.2706422   0.40825688]
 [ 0.0412844  -0.07798165  0.06880734]
 [ 0.39908257 -0.08715596 -0.33486239]]
'''
print(np.dot(a,b))
'''
[[ 1.00000000e+00  1.66533454e-16 -4.99600361e-16]
 [ 2.22044605e-16  1.00000000e+00 -1.11022302e-15]
 [ 5.55111512e-17  5.55111512e-17  1.00000000e+00]]
'''

# read files ........

In [ ]:
# loadtxt(location, dtype, skiprows, usecols)
file_path = r"/media//elsayedelmandoh//Rio//Courses//Python//Coding//loadtxt.txt"
dtype1 = np.dtype([('gender','S1'),('height','f8')])
print(np.loadtxt(file_path,dtype= dtype1,skiprows = 9, usecols = (1,3)))
'''
[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]
'''
# import os
# print(os.path.isfile(d))
# print(np.loadtxt(r"/media//elsayedelmandoh//Rio//Courses//Python//Coding//loadtxt.txt",dtype= [('gender','S1'),('height','f8')],skiprows = 9, usecols = (1,3)))

In [ ]:
file_path = r"/media//elsayedelmandoh//Rio//Courses//Python//Coding//008-mod_numpy//student_data.txt"
print(np.loadtxt(file_path,dtype= [('height','S1')],skiprows = 9, usecols = (3)))
'''
[(b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',)
 (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',) (b'1',)
 (b'1',)]
'''

In [ ]:
file_path = r"/media//elsayedelmandoh//Rio//Courses//Python//Coding//008-mod_numpy//median_age"
a , b , c = np.loadtxt(file_path,unpack=True,skiprows=3)
# import os
# print(os.path.isfile(file_path))
print(a) # [1890. 1900. 1910. 1920. 1930.]
print(b) # [26.1 25.9 25.1 24.6 24.3]
print(c) # [22.  21.9 21.6 21.2 21.3]

In [ ]:
file_path = r"/media//elsayedelmandoh//Rio//Courses//Python//Coding//008-mod_numpy//subject_number.txt"
dtype1 = np.dtype([('id','u8'),('gender','S1'),('black','f8'),('color','f8')])
print(np.genfromtxt(file_path,dtype= dtype1,delimiter=',',missing_values='X'))
# between data is ,
# ignore x
'''
[(18446744073709551615, b' ',   nan,   nan)
 (                   1, b'F', 18.72, 31.11)
 (                   2, b'F', 21.14, 52.47)
 (                   3, b'F', 19.38, 33.9 )]
'''

# polynomial 

In [ ]:
# np.polynomial.Polynomial
pln = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100,120,140,160])
y = np.array([0,2,4,6,8,10,12,14,16])
# must be x and y are same lenght
points , status = pln.fit(x,y,1,full=True)
'''
1 > equation from one degree
full > draw all points
'''
print(points) # 8.000000000000004 + 7.999999999999998·x¹
'''
Y = mX + a
m > slop 
a > level y when x = 0
then 
Y = 7.9X**1 + 8.0
'''

In [ ]:
# np.polynomial.Polynomial
pln = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100,120,140,160])
y = np.array([0,2,4,6,8,10,12,14,16])
# must be x and y are same lenght
points , status = pln.fit(x,y,2,full=True)
'''
1 > equation from two degree
full > draw all points
'''
print(points) # 8.000000000000004 + 8.0·x¹ - 4.2726130004827435e-15·x²
'''
Y = mX + a
m > slop 
a > level y when x = 0
then 
Y = 4.2X**2 + 8.0X**1 + 8.0
'''

In [ ]:
# np.polynomial.Polynomial
pln = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100,120,140,160])
y = np.array([0,2,4,6,8,10,12,14,16])
# must be x and y are same lenght
points , status = pln.fit(x,y,3,full=True)
'''
1 > equation from three degree
full > draw all points
'''
print(points) # 8.000000000000005 + 7.999999999999993·x¹ - 6.4089195007241145e-15·x² -1.9678956988336473e-15·x³
'''
Y = mX + a
m > slop 
a > level y when x = 0
then 
Y = -1.9X**3 -6.4X**2 + 7.9X + 8.0
'''

In [ ]:
# polyfit
x = np.array([0,20,40,60,80,100,120,140,160])
y = np.array([0,2,4,6,8,10,12,14,16])
print(np.polyfit(x,y,2)) # [3.42368933e-19 1.00000000e-01 0.00000000e+00]

In [ ]:
# poly1d() : to generate equations
print(np.poly1d((7))) # y = 7
print(np.poly1d((7,2))) # y = 7x + 2
print(np.poly1d((7,3,5))) # y = 7x**2 + 3x + 5
print(np.poly1d((5,9,6,2.5))) # y = 5x**3 + 9x**2 + 6x + 2.5
print(np.poly1d((9,5,4.3,6.1,22))) # y = 9x**4 + 5x**3 + 4.3x**2 + 6.1x + 22

In [ ]:
# ploy1d with x = number
eq = np.poly1d((2,5,7)) # y = 2x**2 + 5x + 7
print(eq(0)) # 7 : 2*0**2 + 5*0 + 7
print(eq(5)) # 82  : 2*5**2 + 5*5 + 7

In [ ]:
# polyval()
print(np.polyval((1,2),5)) # y = x + 2 = 5 + 2 + 7 
print(np.polyval((5,2,1),3)) # y = 5x**2 + 2x + 1 = 5*3**2 + 2*3 + 1 =  52

In [ ]:
# polyder(equation , count of dev) : poly derevative
print(np.polyder(np.poly1d((1,2,3)))) # y = x**2 + 2x + 3 = 2x + 2
print(np.polyder(np.poly1d((1,2,3,7))) , 2) # y = x**3 + 2x**2 + 3x + 7 = 3x**2 + 4x + 3
print(np.polyder(np.poly1d((1,2,3,4,5))) , 3) # 4x**3 + 6x**2 + 6x + 4

In [ ]:
# ployint(equation, count of int) : poly integration
print(np.polyint(np.poly1d((1,2,3)))) # 0.3333x**3 + 1x**2 + 3x
print(np.polyint(np.poly1d((1,2,3,7))) , 2) # 0.25x**4 + 0.6667x**3 + 1.5x**2 + 7x
print(np.polyint(np.poly1d((1,2,3,4,5))) , 3) # 0.2x**5 + 0.5x**4 + 1x**3 + 2x**2 + 5x

In [ ]:
# roots((equation))
'''
one root for equation of one degree
two roots for equations of two degree
three roots for equations of three degree
...
...
...
'''
print(np.roots(np.poly1d((1,2)))) # [-2]
print(np.roots(np.poly1d((1,2,3)))) # [-1.+1.41421356j -1.-1.41421356j]
print(np.roots(np.poly1d((1,2,3,7))) , 2) # [-2.13249369+0.j          0.06624684+1.81056712j  0.06624684-1.81056712j] 
print(np.roots(np.poly1d((1,2,3,4,5))) , 3) # [-1.28781548+0.85789676j -1.28781548-0.85789676j  0.28781548+1.41609308j 0.28781548-1.41609308j]

# date time 

In [ ]:
# datetime
print(np.datetime64("2002-06-18")) # 2002-06-18
print(np.datetime64("2002-06-18") + np.arange(30)) 
'''
add 30 day on date time
['2002-06-18' '2002-06-19' '2002-06-20' '2002-06-21' '2002-06-22'
 '2002-06-23' '2002-06-24' '2002-06-25' '2002-06-26' '2002-06-27'
 '2002-06-28' '2002-06-29' '2002-06-30' '2002-07-01' '2002-07-02'
 '2002-07-03' '2002-07-04' '2002-07-05' '2002-07-06' '2002-07-07'
 '2002-07-08' '2002-07-09' '2002-07-10' '2002-07-11' '2002-07-12'
 '2002-07-13' '2002-07-14' '2002-07-15' '2002-07-16' '2002-07-17']
''' 

In [ ]:
# datetime
print(np.datetime64("2002-06-18")) # 2002-06-18
print(np.datetime64("2002-06-18") - np.arange(30)) 
'''
mins 30 day on date time
['2002-06-18' '2002-06-17' '2002-06-16' '2002-06-15' '2002-06-14'
 '2002-06-13' '2002-06-12' '2002-06-11' '2002-06-10' '2002-06-09'
 '2002-06-08' '2002-06-07' '2002-06-06' '2002-06-05' '2002-06-04'
 '2002-06-03' '2002-06-02' '2002-06-01' '2002-05-31' '2002-05-30'
 '2002-05-29' '2002-05-28' '2002-05-27' '2002-05-26' '2002-05-25'
 '2002-05-24' '2002-05-23' '2002-05-22' '2002-05-21' '2002-05-20']
''' 

In [ ]:
# my age as days
print(np.datetime64("2022-09-01") - np.datetime64("2002-06-18")) # 7380 days wooow 

In [ ]:
# fromfunction(lambda , shape) shape = matrix
print(np.fromfunction(lambda i: i**3 , shape = (10,))) # [  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]

In [ ]:
print(np.fromfunction(lambda x, y: x*y , shape = (10,4)))
# x : from 0 to 9 
# y : from 0 to 3
# i + all values of j 

In [ ]:
print(np.fromfunction(lambda x, y , z: x+y+z , shape = (2,4,5), dtype= int))
# x : from 0 and 1
# y : from 0 to 3
# z : from 0 to 4

In [ ]:
def fun(i):
    return i % 2 == 0

print(np.fromfunction(fun , (20,) , dtype = int)) # not include 20
'''
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
'''

# Electro pi

fansy indexing

In [22]:
import numpy as np
lst= np.random.randint(0, 20, (4,5))
lst

array([[ 2, 19, 16, 14,  1],
       [16,  3,  1,  1,  1],
       [19, 14,  7, 19,  3],
       [11,  8, 12,  0, 19]])

In [23]:
fans_index= ((0,1), (3))
lst[fans_index]

array([14,  1])

add new dimension

In [30]:
lst= np.random.randint(3, 10, (1,7))
lst

array([[7, 3, 9, 9, 6, 9, 6]])

In [31]:
lst.shape

(1, 7)

In [32]:
# add all values as columns and new dimensions as row
lst = lst[:, np.newaxis]
lst

array([[[7, 3, 9, 9, 6, 9, 6]]])

In [34]:
lst.shape

(1, 1, 7)

In [35]:
lst = lst[np.newaxis, :]
lst

array([[[[7, 3, 9, 9, 6, 9, 6]]]])

In [36]:
lst.shape

(1, 1, 1, 7)