<h1>Linear Algebra ITI</h1>

In [2]:
import numpy as np

In [3]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))

In [4]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [5]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

In [6]:
# transpose
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [7]:
# matrix inverse
my_first_inverse = my_first_matrix.I
my_first_inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [8]:
#should return inverse; floating point values "almost" equal zero
my_first_matrix * my_first_inverse

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
        [ 5.55111512e-17, -1.38777878e-16,  1.00000000e+00]])

In [9]:
# create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Solve simultaneous linear equations

In [10]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [11]:
# not efficient; use only for small matrices
solution = my_first_inverse * right_hand_side
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [12]:
# confirm that solution is correct
my_first_matrix * solution - right_hand_side

matrix([[ 0.00000000e+00],
        [-3.55271368e-15],
        [ 7.10542736e-15]])

In [13]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [ ]:
#2x+5y+4z = 10
#x-y+4z = 20
#-4x+3y-z = 5

In [21]:
coeff_matrix = np.array([[2, 5, 4], [1, -1, 4], [-4, 3, -1]])
rh_side = np.matrix([[10], [20], [5]])

In [20]:
coeff_matrix.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'

In [22]:
solve(coeff_matrix, rh_side)

matrix([[-3.46534653],
        [-1.08910891],
        [ 5.59405941]])

In [11]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))