# ITI

In [2]:
import numpy as np

In [3]:
# create 1-D array with values from 1 to 6
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [4]:
a2 = [1,2,3,4,5,6]
print(a2)

[1, 2, 3, 4, 5, 6]


In [5]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a)
# 2D arrays

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# Acessing Array Elements -> index of element
# []
a[2]

array([ 9, 10, 11, 12])

In [7]:
[[0.,0.,0.],
 [1.,1.,1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [8]:
# np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
# Array of Zeros
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [11]:
# (3,4)
# for a 2-dimensional array of shape (3,4) filled with zeros
z_2D = np.zeros((3,4))
z_2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
z_3D = np.zeros((2,3,2))
z_3D

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
# Array filled with 1's
s = np.array([1,1])
s

array([1, 1])

In [14]:
# np.ones(length, dtype)
s2 = np.ones(4, dtype=float)
s2

array([1., 1., 1., 1.])

In [15]:
# np.empty(length)
e = np.empty(10)
e

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.06811490e-306,
       1.89146896e-307, 7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
       1.29061142e-306, 5.53353523e-322])

In [16]:
e = np.random.rand(10)
e

array([0.69047856, 0.82015941, 0.35068751, 0.75707802, 0.79629753,
       0.43138949, 0.14140517, 0.55237649, 0.96602532, 0.61798286])

In [17]:
# np.random.randint -> integer number -> (start, end, size)
e = np.random.randint(0,10 , size = 6)
e

array([0, 3, 1, 8, 5, 6])

In [18]:
# Array within range
# create an array with number from 0 to 9 (stop value is exclusive)
array_arrange = np.arange(10)
array_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# np.linspace(start, end, size)
ls = np.linspace(0,1,5)
ls

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
i = np.arange(0,10,2)
i

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# Specifing your data type
# dtype
x = np.ones(2, dtype = np.float64)
x

array([1., 1.])

In [23]:
# Adding , removing , sort elements
# np.sort()
# np.concatenate()

arr = np.array([2,1,5,3,7,4,6,8])

In [24]:
# ascending order
sarr = np.sort(arr)
sarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [26]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [27]:
np.sort(a, axis = None)

array([1, 1, 3, 4])

In [28]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [29]:
np.sort(a, axis=1)

array([[1, 4],
       [1, 3]])

In [30]:
# kind of sort 
# argsort -> which is an indirect sort along a specified axis
# lexsort -> which is an indirect stable sort on multiple keys
# searchsorted -> which will find elements in a sorted array
# partirion -> which is a partial sort

In [31]:
# concatinating 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])


In [32]:
arr3 = np.concatenate((arr1,arr2))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
array3 = np.array([[1,2],[3,4]])
array4 = np.array([[5,6],[7,8]])

# concatenate the two arrays along axis 0 (joining them vertically)
concatenate_array_2d = np.concatenate((array3,array4), axis = 0)
print(concatenate_array_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [35]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# ndarray.ndim, ndarray.size, ndarray.shape
# ndarray.ndim -> will tell you the number of axes or dimensions of the array
# ndarray.size -> will tell you total number of elements of the array
# ndarray.shape -> will display a tuple of integers that indicate number of elements -> (2,3)
# you have 2-D array with 2 rows and 3 columns the shape of your array is (row, col) -> (2,3) 

In [38]:
a = np.arange(6)

In [39]:
a

array([0, 1, 2, 3, 4, 5])

In [40]:
np.reshape(a, newshape=(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
# convert 1-D array into 2-D array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [43]:
a.shape

(6,)

In [45]:
# you can use np.newaxis to add new axis
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [46]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [47]:
# or column vector insert axis along with the second dimension
col_vector = a[: ,np.newaxis]
col_vector.shape

(6, 1)

In [51]:

"""
you can also expand an array by inserting a new axis at specified position with np.expand_dims

0 -> index means row
1 -> index means column
"""
print()

In [52]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [53]:
a.shape

(6,)

In [57]:
b = np.expand_dims(a, axis = 1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [58]:
b = np.expand_dims(a, axis = 0)
print(b.shape)
print(b)

(1, 6)
[[1 2 3 4 5 6]]


In [59]:
# Indexing and Slicing 
# subset , slice, index


In [60]:
data = np.array([1,2,3])


In [61]:
data[1]

2

In [62]:
data[0:2]

array([1, 2])

In [63]:
data[1:]

array([2, 3])

In [64]:
data[-2]

2

In [65]:
data[-2:]

array([2, 3])

In [68]:
data[:-1]

array([1, 2])

In [70]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
# select all numbers that are equal to or greater than 5

In [73]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [87]:
c = a[(a > 2) & (a<11)]

In [88]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
x = (a > 5) | (a==5)
x

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
print(5>6)

False


In [90]:
print(6>5)

True


In [91]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
a[0]

array([1, 2, 3, 4])

In [93]:
b = np.nonzero(a<5)

In [94]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [95]:
print(a[b])

[1 2 3 4]


In [96]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [98]:
# Vertical stack
# horizontal stack
# np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [99]:

a1 = np.array([[1,1],
              [2,2]])

a2 = np.array([[3,3],
              [4,4]])

In [100]:
a1

array([[1, 1],
       [2, 2]])

In [101]:
a2

array([[3, 3],
       [4, 4]])

In [102]:
np.vstack(a2)

array([[3, 3],
       [4, 4]])

In [103]:
np.hstack(a1)

array([1, 1, 2, 2])

In [104]:
# Split

In [105]:
a = np.arange(1,25)

In [106]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [107]:
a.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [108]:
a = np.arange(1,25).reshape(2,12)

In [109]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [110]:
x = a 

In [111]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [112]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [113]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
b2 = a.copy()
print(b2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
b2[0][0] = 77
b2

array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [118]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [119]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
a = np.array([1,2,3,4])
a.sum()

10

In [121]:
# sum(axis = row | col)
b = np.array([[1,5],
             [2,2]])
b

array([[1, 5],
       [2, 2]])

In [122]:
# rows => axis = 0
b.sum(axis=0)

array([3, 7])

In [123]:
b.sum(axis=1)

array([6, 4])

In [124]:
print(np.__version__)

1.24.2


In [133]:
# Array Attributes

a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [134]:
a.ndim

3

In [135]:
a.shape

(2, 3, 4)

In [136]:
a.size

24

In [137]:
a.dtype

dtype('int32')

In [138]:
a.itemsize

4

In [139]:
type(a)

numpy.ndarray

In [140]:
# Boolean Masking
my_vec = np.array([-17,-4,0,2,21,37,105])
my_vec

array([-17,  -4,   0,   2,  21,  37, 105])

In [141]:
zero_mod_7_mask = (my_vec % 7 == 0)
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [144]:
list_2 = [0,0,1,0,1,0,1]
zero_mod_7_mask_2 = np.array(list_2)
type(zero_mod_7_mask_2)

numpy.ndarray

In [145]:
sub_array = my_vec[zero_mod_7_mask]
sub_array

array([  0,  21, 105])

In [147]:
person_data = [['name','h1'],['height','f8'],['height','f8']]
pepole_array = np.zeros((4), dtype=person_data)
pepole_array

TypeError: Field elements must be 2- or 3-tuples, got '['name', 'h1']'

In [152]:
person_data = [('name','S6'),('height','f8'),('weight', 'f8'),('age','i8')]
person_data

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [153]:
pepole_array = np.zeros((4), dtype=person_data)
pepole_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])