Elsayed Mohamed Elmandoh

In [13]:
import numpy as np

1- Create a NumPy program to create a 3x3 identity matrix


In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2- Create a NumPy program to generate 5 random number between 0 and 1


In [15]:
np.random.rand(5)

array([0.93182693, 0.48782941, 0.52998847, 0.48550573, 0.16358936])

3- Write a NumPy program to append values to the end of an array.

Expected Output:

Original array: 
[10, 20, 30]
After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90]

In [16]:
orgn = np.array([10, 20, 30])
apnd = np.array([40, 50, 60, 70, 80, 90])

np.append(orgn, apnd)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])