#### Task 1: NumPy Exploration

1. **NumPy Basics:**
   - Import the NumPy library.
   - Create a 1D NumPy array named `arr_1d` with elements `[1, 2, 3, 4, 5]`.
   - Create a 2D NumPy array named `arr_2d` with the following elements:
     ```
     [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
     ```




In [58]:
import numpy as np

In [59]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d

array([1, 2, 3, 4, 5])

In [60]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. **Array Operations:**
   - Perform the following operations on `arr_1d`:
     - Add 10 to each element.
     - Subtract 2 from each element.
     - Multiply each element by 3.
     - Divide each element by 2.



In [61]:
arr_1d_plus_10 = arr_1d + 10
arr_1d_plus_10

array([11, 12, 13, 14, 15])

In [62]:
arr_1d_minus_2 = arr_1d - 2
arr_1d_minus_2

array([-1,  0,  1,  2,  3])

In [63]:
arr_1d_times_3 = arr_1d * 3
arr_1d_times_3

array([ 3,  6,  9, 12, 15])

In [64]:
arr_1d_divided_by_2 = arr_1d / 2
arr_1d_divided_by_2

array([0.5, 1. , 1.5, 2. , 2.5])

3. **Array Indexing and Slicing:**
   - Access the element at the 2nd index of `arr_1d`.
   - Slice `arr_1d` to get a subarray containing elements from index 1 to 3.
   - Access the element at the 2nd row and 3rd column of `arr_2d`.
   - Slice `arr_2d` to get a subarray containing the first two rows and the last two columns.



In [65]:
element_at_2nd_index = arr_1d[1]
element_at_2nd_index

2

In [66]:
subarray_1d = arr_1d[1:4]
subarray_1d

array([2, 3, 4])

In [67]:
element_at_2nd_row_3rd_column = arr_2d[1, 2]
element_at_2nd_row_3rd_column

6

In [68]:
subarray_2d = arr_2d[:2, 1:]
subarray_2d

array([[2, 3],
       [5, 6]])

4. **Array Functions and Statistics:**
   - Calculate and print the sum, mean, and maximum value of `arr_1d`.
   - Calculate and print the sum along each column and mean along each row of `arr_2d`.


In [69]:
sum_arr_1d = np.sum(arr_1d)
sum_arr_1d

15

In [70]:
mean_arr_1d = np.mean(arr_1d)
mean_arr_1d

3.0

In [71]:
max_arr_1d = np.max(arr_1d)
max_arr_1d

5

In [72]:
sum_columns_arr_2d = np.sum(arr_2d, axis=0) # 0 : cols , 1 : rows
sum_columns_arr_2d


array([12, 15, 18])

In [73]:
mean_rows_arr_2d = np.mean(arr_2d, axis=1)
mean_rows_arr_2d

array([2., 5., 8.])


5. **Element-wise Operations and Broadcasting:**
   - Perform the following element-wise operations on `arr_1d`:
     - Square each element.
     - Take the square root of each element.
     - Calculate the exponential of each element.
   



In [74]:
squared_arr_1d = np.square(arr_1d)
squared_arr_1d

array([ 1,  4,  9, 16, 25])

In [75]:
sqrt_arr_1d = np.sqrt(arr_1d)
sqrt_arr_1d

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [76]:
exp_arr_1d = np.exp(arr_1d)
exp_arr_1d

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

#### Task 2: Pandas Exploration


6. **Pandas Basics:**
   - Import the Pandas library.
   - Create a Pandas Series named `series_1d` with elements `[10, 20, 30, 40, 50]`.
   - Create a Pandas DataFrame named `df` with the following data:
     ```
       Name  Age  Grade
     0  John   25    A
     1  Jane   22    B
     2  Mark   28    C
     ```




In [77]:
import pandas as pd

In [78]:
series_1d = pd.Series([10, 20, 30, 40, 50])

data = {'Name': ['John', 'Jane', 'Mark'],
        'Age': [25, 22, 28],
        'Grade': ['A', 'B', 'C']}

df = pd.DataFrame(data)

7. **Data Manipulation with Pandas:**
   - Display the first 5 rows of the DataFrame using `df.head()`.
   - Filter the DataFrame to show only rows where the 'Age' column is greater than 25.
   - Sort the DataFrame based on the 'Grade' column in ascending order.


In [79]:
df.head()

Name  Age Grade
0  John   25     A
1  Jane   22     B
2  Mark   28     C

In [80]:
df[df['Age'] > 25]

Name  Age Grade
2  Mark   28     C

In [81]:
df.sort_values(by='Grade')

Name  Age Grade
0  John   25     A
1  Jane   22     B
2  Mark   28     C

8. **Basic Data Exploration:**
   - Display information about the DataFrame using `df.info()`.
   - Generate descriptive statistics for numeric columns using `df.describe()`.


In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Grade   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [83]:
df.describe()

Age
count   3.0
mean   25.0
std     3.0
min    22.0
25%    23.5
50%    25.0
75%    26.5
max    28.0

In [84]:
loaded_data = pd.read_excel('data.xls')
loaded_data.head()

Unnamed: 0  Math   Physics  French  Chemistry
0          a     1       NaN      11         16
1          b     2   7.00000      12         17
2          c     3   8.45500      13         18
3          d    17   9.65651      14         19
4          e    12  10.00000      15         20

In [85]:
loaded_data.info

<bound method DataFrame.info of   Unnamed: 0  Math   Physics  French  Chemistry
0          a     1       NaN      11         16
1          b     2   7.00000      12         17
2          c     3   8.45500      13         18
3          d    17   9.65651      14         19
4          e    12  10.00000      15         20
5          a     1   7.00000      11         16
6          b     4  15.00000      13         17>