In [ ]:
import numpy as np

In [ ]:
# slice in list 
ls = [1,2,3,5,4,8,9]
print(ls[1])
print(ls[-2])
# [start:end:step]
print(ls[::2])

In [ ]:
# slice in array 1D

a = np.arange(2,9) # [2 3 4 5 6 7 8]
print(a)
print(a[3]) # 5
print(a[-1]) # 8
print(a[::-2]) # [8 6 4 2]

In [ ]:
# slice in array 2D

a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[3]) # [19 20 21 22 23 24]
print(a[-1]) #  [31 32 33 34 35 36]
print(a[::-2])
'''
[[31 32 33 34 35 36]
 [19 20 21 22 23 24]
 [ 7  8  9 10 11 12]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[3,2]) # 21
print(a[2,:]) #  [13 14 15 16 17 18]

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

print(a[:,2]) #  [3 9 15 21 27 33]

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[: , 2:4])
'''
[[3 4]
 [9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[1:4 , 1:3])
'''
[[ 8  9]
 [14 15]
 [20 21]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[:,:])
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
print(a[::-1 , ::-1])
'''
[[36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
'''

In [ ]:
ls = [1,2,3]
ls[1] = 5
print(ls)

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[2 , 4] = 0
print(a)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 0 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[:,4] = 0
print(a)
'''
[[ 1  2  3  4  0  6]
 [ 7  8  9 10  0 12]
 [13 14 15 16  0 18]
 [19 20 21 22  0 24]
 [25 26 27 28  0 30]
 [31 32 33 34  0 36]]
'''

In [ ]:
a = np.arange(1,37).reshape(6,6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''
a[3,:] = 0
print(a)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [ 0  0  0  0  0  0]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
'''

In [ ]:
a = np.arange(16).reshape(4,4)
'''
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]
'''
b = a[2: , 3:] # change with a
print(b)
a[:,:] = 7
print(a)
print(b)

In [ ]:
a = np.arange(16).reshape(4,4)
'''
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]
'''
b = a[2: , 3:].copy() # not change with a
print(b)
a[:,:] = 7
print(a)
print(b)

In [ ]:
# dtype(matrix)
a = np.arange(7) # [0 1 2 3 4 5 6]
print(a.dtype) # int64 > integer 64 bit

b = np.array(['a', 'b'])
print(b.dtype) # U1

In [ ]:
# trace(matrix) collection diagonal 
print(np.trace(np.eye(5))) # 1+1+1+1+1 = 5 
'''
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
'''

In [ ]:
a = np.arange(9).reshape(3,3)
'''
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(np.trace(a)) # 12

In [ ]:
a = np.arange(8).reshape((2,2,2))
'''[[[0 1] # **
    [2 3]]

    [[4 5]
    [6 7]]]''' # **
print(np.trace(a))

In [ ]:
a = np.arange(27).reshape((3,3,3))
'''[[[ 0  1  2] **
     [ 3  4  5]
     [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14] **
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] ** '''
# print(a)
print(np.trace(a)) # [36 39 42]

In [ ]:
# vstack((matrix1,matrix2)) : must equal cols
a = np.arange(8).reshape(2,4)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
b = 3*np.arange(8).reshape(2,4)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
avb = np.vstack((a,b))
print(avb)
'''
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  3  6  9]
 [12 15 18 21]]
'''

In [ ]:
# hstack((matrix1,matrix2)) : must equal rows
a = np.arange(8).reshape(2,4)
'''
[[0 1 2 3]
 [4 5 6 7]]
'''
b = 3*np.arange(8).reshape(2,4)
'''
[[ 0  3  6  9]
 [12 15 18 21]]
'''
ahb = np.hstack((a,b))
print(ahb)
'''
[[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]]
'''

In [ ]:
b = np.ones((5,5))
b[1:-1 , 1:-1] = 0
print(b)
print(np.count_nonzero(b))

In [ ]:
# dot(matrix) : multiply matrix
#  (2,3) * (3,5) = out => (2,5)
a = np.arange(6).reshape(2,3)
'''
[[0, 1, 2],
[3, 4, 5]]
'''
b = np.arange(6).reshape(3,2)
'''
[[0, 1],
[2, 3],
[4, 5]]
'''
print(np.dot(a,b))
'''
[[10 13]
 [28 40]]
'''

In [ ]:
# sum(matrix) : sum matrix
a = np.arange(12).reshape(3,4)
'''[[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]]'''
print(np.sum(a)) # 66
print(np.sum(a,axis = 1)) # rows => [6 22 38]
print(np.sum(a,axis = 0)) # cols =>[12 15 18 21]

In [ ]:
# add(matrix , number, out)
a = np.arange(7)
'''
[0 1 2 3 4 5 6]
'''
b = np.add(a,7) # [7 7 7 7 7 7 7]
print(b)
# [ 7  8  9 10 11 12 13]

In [ ]:
# add.reduce(matrix) return collection numbers
a = np.arange(7) # [0 1 2 3 4 5 6]
print(np.add.reduce(a)) # 21

In [ ]:
# add.accumulate(matrix) return matrix with collection all back 
a = np.arange(2,7) # [2 3 4 5 6]
print(np.add.accumulate(a))
'''
[2 3+2 4+3+2 5+4+3+2 6+5+4+3+2] =  [2 5 9 14 20]
'''

In [ ]:
# multiply(matrix , number, out )
a = np.arange(7)
'''
[0 1 2 3 4 5 6]
'''
b = np.zeros(7)
'''
[0. 0. 0. 0. 0. 0. 0.]
'''
np.multiply(a,10,out=b)
print(b)
'''
[ 0. 10. 20. 30. 40. 50. 60.]
'''

In [ ]:
# multiply.reduce(matrix) return multiply all numbers
a = np.arange(2,7) # [2 3 4 5 6]
print(np.multiply.reduce(a)) # 720

In [ ]:
# multiply.accumulate(matrix) ~ same factorial
a = np.arange(1,7) # [1 2 3 4 5 6]
print(np.multiply.accumulate(a))
'''
[1 2*1 3*2*1 4*3*2*1  5*4*3*2*1 6*5*4*3*2*1] = [1 2 6 24 120 720]
'''

In [ ]:
# power(matrix , power, out)
a = np.arange(7)
# [0 1 2 3 4 5 6]

c = np.power(a,3)
print(c)
# [  0   1   8  27  64 125 216]

In [ ]:
# sort(matrix , axis=0 or 1)
a = np.random.randint(4,9,size = 12).reshape(3,4)
print(a)
print()
print(np.sort(a, axis=0)) # cols
print()
print(np.sort(a, axis=1)) # rows

In [ ]:
# linalg.det(matrix)
a = np.arange(1,5).reshape(2,2)
'''
[[1 2]
 [3 4]]
'''
print(np.linalg.det(a)) # 1*4 - 2*3 = -2.0

b = np.arange(9).reshape(3,3) 
'''
  - + -
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(np.linalg.det(b)) # -0*(4*8 - 5*7) +1*(3*8 - 5*6) -2*(3*7 - 4*6) = 0.0

In [ ]:
# linalg.inv(matrix) : linear algebra function
a = np.random.randint(5,15,size =9).reshape(3,3)
print(a)
b = np.linalg.inv(a)
print(np.linalg.inv(a))